// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFolder(arg1:string):Promise<void>;

export function BackupAll():Promise<void>;

export function BackupNow(arg1:string):Promise<void>;

export function GetStatus():Promise<main.StatusView>;

export function ListSnapshots():Promise<Array<main.SnapshotView>>;

export function PickFolder():Promise<string>;

export function PickRestoreTarget():Promise<string>;

export function RemoveFolder(arg1:string):Promise<void>;

export function RestoreFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetFolderBackup(arg1:string,arg2:boolean):Promise<void>;

export function SnapshotTree(arg1:string):Promise<Array<main.NodeView>>;
