// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function BackupAll() {
  return window['go']['main']['App']['BackupAll']();
}

export function BackupNow(arg1) {
  return window['go']['main']['App']['BackupNow'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickRestoreTarget() {
  return window['go']['main']['App']['PickRestoreTarget']();
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function RestoreFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreFile'](arg1, arg2, arg3);
}

export function SetFolderBackup(arg1, arg2) {
  return window['go']['main']['App']['SetFolderBackup'](arg1, arg2);
}

export function SnapshotTree(arg1) {
  return window['go']['main']['App']['SnapshotTree'](arg1);
}
